### PR TITLE
Integrate All branches.

### PR DESCRIPTION
**Pull request by marcusteh1238**

### CODE REVIEW

**Comment by WeomuCat** [comment]
Looks good, but this commit (https://github.com/AY1920S1-CS2103T-F12-1/main/commit/e9e5ec93a7b2029e584c5283e297c1ee505d451c) from branch-ui seems to be missing.

Will leave a review after I complete branch-commands :)

**Comment by marcusteh1238** [comment]
> Looks good, but this commit ([e9e5ec9](https://github.com/AY1920S1-CS2103T-F12-1/main/commit/e9e5ec93a7b2029e584c5283e297c1ee505d451c)) from branch-ui seems to be missing.
> 
> Will leave a review after I complete branch-commands :)

There are warnings popping up when I run the program. Waiting on @Kyzure to fix those first before adding his branch to the PR.

**Comment by marcusteh1238** [comment]
Left with branch-undo, branch-notifications. Final update to branch-ui may be considered for integration.

**Comment by WeomuCat** [comment]
> Left with branch-undo, branch-notifications. Final update to branch-ui may be considered for integration.

`branch-commands` has not been fully merged yet as well

**Comment by marcusteh1238** [comment]
Ok, merged the latest commit in branch-commands. Thanks for noticing!

**Pull request merged**
